server:
  port: 8888

#http://localhost:8888/h2-console
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:ecommerce
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create